# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redmine_project_url', models.CharField(max_length=100)),
                ('redmine_project_id', models.IntegerField()),
                ('redmine_project_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=75)),
                ('project_desc', models.CharField(max_length=200, verbose_name='Project description')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tm_cap', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Time and Materials cap')),
                ('deadline', models.DateField()),
                ('analysis_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Analysis %')),
                ('admin_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Admin %')),
                ('completed_on', models.DateField(verbose_name='Completion date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.Product')),
            ],
        ),
    ]
