# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='product',
            new_name='product_id',
        ),
    ]
