# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_auto_20160825_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='product_id',
        ),
    ]
