# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='project',
            name='completed_on',
            field=models.DateField(blank=True, verbose_name='Completion date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='redmine_project_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='tm_cap',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Time and Materials cap'),
        ),
    ]
