# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0008_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='redmine_project_url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
