# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0012_auto_20160826_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed_on',
            field=models.DateField(blank=True, null=True, verbose_name='Completion date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
