# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0013_auto_20160826_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_hours_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total hours spent'),
        ),
    ]
