# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0014_project_total_hours_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_import_timestamp', models.DateTimeField(blank=True, null=True)),
                ('most_recent_time_entry', models.IntegerField()),
            ],
        ),
    ]
