# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0015_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
