# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0016_delete_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='recent_hours_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Recent hours spent'),
        ),
    ]
