# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0017_project_recent_hours_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redmine_project_id', models.IntegerField()),
            ],
        ),
    ]
