# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0019_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_admin_hours_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total admin hours spent'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_analysis_hours_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Total analysis hours spent'),
        ),
    ]
