# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0022_auto_20170718_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(blank=True, to='pm.Staff'),
        ),
    ]
