# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0023_auto_20170718_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='email',
            new_name='staff_email',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='staff_name',
        ),
    ]
