# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0024_auto_20170720_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_abvr',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_position',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
