# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0025_auto_20170725_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_position',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
