# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0027_projectlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlog',
            name='project',
        ),
        migrations.AddField(
            model_name='projectlog',
            name='redmine_project_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
