# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-19 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0028_auto_20170818_1452'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectLog',
            new_name='ProjectLogEntry',
        ),
    ]
