# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0029_auto_20170818_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlogentry',
            name='entry_type',
            field=models.BooleanField(default=False),
        ),
    ]
