# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0031_auto_20170826_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlogentry',
            name='entry_action',
            field=models.CharField(choices=[('UP', 'Update'), ('DC', 'Decision')], default='UP', max_length=2),
        ),
        migrations.AlterField(
            model_name='projectlogentry',
            name='entry_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='projectlogentry',
            name='entry_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
