# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0032_auto_20170826_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlogentry',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
