# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0033_auto_20170826_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlogentry',
            name='entry_text',
            field=models.TextField(max_length=225),
        ),
    ]
