# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-01 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0034_auto_20170827_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlogentry',
            name='redmine_project_id',
            field=models.IntegerField(default=0),
        ),
    ]
