# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-01 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0035_auto_20170901_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlogentry',
            name='redmine_project_id',
        ),
        migrations.AddField(
            model_name='projectlogentry',
            name='redmine_identifier',
            field=models.IntegerField(default=10),
        ),
    ]
