# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-01 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0037_auto_20170901_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlogentry',
            name='entry_type',
            field=models.BooleanField(default=False, verbose_name='Meeting?'),
        ),
        migrations.AlterField(
            model_name='projectlogentry',
            name='redmine_identifier',
            field=models.IntegerField(),
        ),
    ]
