# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0038_auto_20170901_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlogentry',
            name='entry_author',
            field=models.CharField(default='', max_length=20),
        ),
    ]
