# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0039_projectlogentry_entry_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlogentry',
            name='entry_text',
            field=models.TextField(max_length=250),
        ),
    ]
